version: "3.7"
services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: metya/vanity_bot
    container_name: vanity_bot
    environment:
      - API_TOKEN
      - GITHUB_TOKEN
      - TIME_OUT
    restart: always
