name: Deploy bot with docker-compose

on:
  push:
    tags:
      - v1.*

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    name: Deploy Vanity Bot
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Deploy compose
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.PUBLIC_KEY }}
          deployment_mode: docker-compose
          args: up -d
          docker_prune: "true"
          pull_images_first: "false"
